apiVersion: v1
kind: Service
metadata:
  name: cloudnorth-frontend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: cloudnorth-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP

